name: My Open Catalogi Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@1.1.1
        with:
          opencatalogi: true
      - name: Create an Open Catalogi page
        uses: OpenCatalogi/opencatalogi-action@1.1.1
        with:
          nl_design_theme_classname: 'open-webconcept-theme'
          pull_from_branche: 'development'
          start_page: 'https://raw.githubusercontent.com/CommonGateway/plugin-object-table/master/README.md'
          favicon_logo: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
          navbar_logo: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
          footer_logo: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
          page_title: "Open Webconcept | Object Table Plugin"
          jumbotron_title: "Object Table Plugin"
          jumbotron_subtitle: "Wordpress tabbelen voor overige objecten"
          jumbotron_description: "
De Objecten Tabellen plugin voor WordPress faciliteert Nederlandse gemeenten bij het publiceren van dynamische en actuele gegevens vanuit hun datawarehouses op hun websites, conform de Overige Objecten Standaard van de VNG. Deze efficiënte tool automatiseert de presentatie van gegevens in tabellen, vereenvoudigt contentbeheer en verbetert de toegankelijkheid van betrouwbare informatie voor burgers, waardoor transparantie en betrokkenheid worden verhoogd."
          jumbotron_image_placement: "right"
          jumbotron_image_url: "https://raw.githubusercontent.com/CommonGateway/plugin-object-table/master/docs/OWC_object_table.png"
          jumbotron_searchform: false
